version: 2
jobs:
  build:
    working_directory: ~/ideal-guid
    docker:
      - image: circleci/node:8.11-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Install Angular CLI
          command: sudo npm install -g @angular/cli@latest
      - run:
          name: test
          command: |
            ng test --code-coverage --watch=false
            sudo npm install -g codeclimate-test-reporter
            codeclimate-test-reporter < ./coverage/lcov.info
      - run:
          name: e2e
          command: ng e2e
      - run:
          name: build
          command: ng build --prod

      - deploy:
          name: Deploy
          command: |
            echo "Echoing random number ${CIRCLE_BRANCH}   [ OK ]"

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
            elif [ "${CIRCLE_BRANCH}" == "production" ]; then
              echo "Yeahhh Echoing random number ${HEROKU_API_KEY} ${HEROKU_APP}"
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git production
            fi
